python-jango/mysite/article/urls.py
from django.urls import path
from . import views


app_name = 'article'
urlpatterns = [
    path('article-column/', views.article_column, name='article_column')
]

python-jango/mysite/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # path()第一个参数为空，表示访问根，又因为在blog应用中，所以访问blog应用的根，即http://127.0.0.1:8000/blog/
    # views.blog_title声明了响应这个请求的函数
    path('', views.blog_title, name='blog_title'),
    path('<int:article_id>/', views.blog_article, name='blog_article')
]

python-jango/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('account/', include('account.urls', namespace='account')),
    path('article/', include('article.urls', namespace='article'))
]

python-jango/mysite/article/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class ArticleColumn(models.Model):
    # 在Django中，模型对象之间的关系可以概括为“一对一”、“一对多”和“多对多”三种关系，分别对应OneToOneField、ForeignKey、ManyToManyField
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='article_column')
    column = models.CharField(max_length=200)
    created = models.DateField(auto_now_add=True)

    def _str_(self):
        return self.column

python-jango/mysite/article/forms.py
from django import forms
from .models import ArticleColumn


class ArticleColumn(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ('column',)

python-jango/mysite/article/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import ArticleColumn
# Create your views here.


@login_required(login_url='/account/login/')
def article_column(request):
    columns = ArticleColumn.objects.filter(user=request.user)
    return render(request, 'article/column/article_column.html', {'columns': columns})

python-jango/mysite/templates/article/column/article_column.html
{% extends "article/base.html" %}
    {% load static %}
    {% block title %}article column{% endblock %}
    {% block content %}
    <div>
        <p class="text-right">
            <button id="add_column" onclick="add_column()" class="btn btn-primary">add column</button>
        </p >
        <table class="table table-hover">
        <tr>
            <td>序号</td>
            <td>栏目名称</td>
            <td>操作</td>
        </tr>
        {% for column in columns %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ column.column }}</td>
            <td>--</td>
        </tr>
        {% empty %}
        <p>还没有设置栏目，太懒了。</p >
        {% endfor %}
        </table>
    </div>
<script type="text/javascript" src='{% static "js/jquery.js" %}'></script>
    <script type="text/javascript" src="{% static 'js/layer.js'%}"></script>
    <script type="text/javascript">
        function add_column(){
            var index = layer.open({
                type:1,
                skin:"layui-layer-rim",
                area: ["400px", "200px"],
                title: "新增栏目",
                content: '<div class="text-center" style="margin-top:20px">
                            <p>请输入新的栏目名称</p >
                            <p><input type=”text”></p >
                          </div>',
                btn:[’确定’, ’取消’],
                yes: function(index, layero){
                    column_name = $('#id_column').val();
                    alert(column_name);
                },
                btn2: function(index, layero){
                    layer.close(index);
                }
            });
        }
    </script>
    {% endblock %}