python-jango/mysite/account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'
urlpatterns = [
    # path('login/', views.user_login, name='user_login')
    # auth_views.LoginView.as_view()是新引入的模块中提供的登录方法
    path('login/', auth_views.LoginView.as_view(template_name='account/login2.html'), name='user_login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html'), name='user_logout'),
    path('register/', views.register, name='user_register'),
    path('password-change/', auth_views.PasswordChangeView.as_view(
        template_name='account/password_change_form.html', # 修改密码的页面模板
        success_url='/account/password-change-done' # 说明了如果密码修改成功，页面跳转对象
    ), name='password_change'),
    path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='account/password_change_done.html'
    ), name='password_change_done'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='account/password_reset_form.html',
        email_template_name='account/password_reset_email.html',
        success_url='account/password-reset-done/'
    ), name='password_reset'),
    path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(
        template_name='account/password_reset_done.html'
    ), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='account/password_reset_confirm.html',
        success_url='/account/password-reset-complete/'
    ), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetConfirmView.as_view(
        template_name='account/password_reset_complete.html'
    ), name='password_reset_complete'),
    path('my-information/', views.myself, name='my_information'),
    path('edit-my-information/', views.myself_edit, name='edit_my_information'),
    path('my-image/', views.my_image, name='my_image')
]

python-jango/mysite/article/urls.py
from django.urls import path
from . import views


app_name = 'article'
urlpatterns = [
    path('article-column/', views.article_column, name='article_column')
]

python-jango/mysite/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # path()第一个参数为空，表示访问根，又因为在blog应用中，所以访问blog应用的根，即http://127.0.0.1:8000/blog/
    # views.blog_title声明了响应这个请求的函数
    path('', views.blog_title, name='blog_title'),
    path('<int:article_id>/', views.blog_article, name='blog_article')
]

python-jango/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('account/', include('account.urls', namespace='account')),
    path('article/', include('article.urls', namespace='article'))
]

python-jango/mysite/article/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class ArticleColumn(models.Model):
    # 在Django中，模型对象之间的关系可以概括为“一对一”、“一对多”和“多对多”三种关系，分别对应OneToOneField、ForeignKey、ManyToManyField
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='article_column')
    column = models.CharField(max_length=200)
    created = models.DateField(auto_now_add=True)

    def _str_(self):
        return self.column

python-jango/mysite/article/forms.py
from django import forms
from .models import ArticleColumn


class ArticleColumn(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ('column',)

python-jango/mysite/article/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import ArticleColumn
# Create your views here.


@login_required(login_url='/account/login/')
def article_column(request):
    columns = ArticleColumn.objects.filter(user=request.user)
    return render(request, 'article/column/article_column.html', {'columns': columns})

python-jango/mysite/templates/article/base.html
{% load static %}
    <! DOCTYPE html>
    <html lang="zh-cn">
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=Edge">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    </head>
    <body>
    <div class="container">
        {% include 'article/header.html' %}
        <div class="col-md-2">
        {% include 'article/leftslider.html' %}
        </div>
      <div class="col-md-10">
      {% block content %}
      {% endblock %}
      </div>
      {% include 'footer.html' %}
  </div>
  </body>
  </html>

python-jango/mysite/templates/article/header.html
{% load static %}
    <div class="container">
        <nav class="navbar navbar-default" role="navigation">
          <div class="navbar-header">
              <a class="navbar-brand" href=" ">
                  <img width="100px" src="{% static 'images/backlogo.png' %}">
              </a>
          </div>
          <div>
              <ul class="nav navbar-nav" role="tablist">
                <li><a href="{% url 'article:article_column' %}">文章管理</a></li>
              </ul>
              <ul class="nav navbar-nav navbar-right" style="margin-right:10px">
                <li><a href="{% url 'blog:blog_title' %}">网站首页</a></li>
                  <li><span>{{ user.username }}</span></li>
                <li><a href="{% url 'account:user_logout' %}">Logout</a></li>
              </ul>
          </div>
      </nav>
    </div>

python-jango/mysite/templates/article/leftslider.html
<div class="bg-info">
    <div class="text-center" style="margin-top: 5px">
        <p>
            <a href="{% url 'article:article_column' %}">栏目管理</a>
        </p>
    </div>
</div>