python-jango/mysite/account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'
urlpatterns = [
    # path('login/', views.user_login, name='user_login')
    # auth_views.LoginView.as_view()是新引入的模块中提供的登录方法
    path('login/', auth_views.LoginView.as_view(template_name='account/login2.html'), name='user_login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html'), name='user_logout'),
    path('register/', views.register, name='user_register'),
    path('password-change/', auth_views.PasswordChangeView.as_view(
        template_name='account/password_change_form.html', # 修改密码的页面模板
        success_url='/account/password-change-done' # 说明了如果密码修改成功，页面跳转对象
    ), name='password_change'),
    path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='account/password_change_done.html'
    ), name='password_change_done'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='account/password_reset_form.html',
        email_template_name='account/password_reset_email.html',
        success_url='account/password-reset-done/'
    ), name='password_reset'),
    path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(
        template_name='account/password_reset_done.html'
    ), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='account/password_reset_confirm.html',
        success_url='/account/password-reset-complete/'
    ), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetConfirmView.as_view(
        template_name='account/password_reset_complete.html'
    ), name='password_reset_complete'),
    path('my-information/', views.myself, name='my_information'),
    path('edit-my-information/', views.myself_edit, name='edit_my_information'),
    path('my-image/', views.my_image, name='my_image')
]

python-jango/mysite/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # path()第一个参数为空，表示访问根，又因为在blog应用中，所以访问blog应用的根，即http://127.0.0.1:8000/blog/
    # views.blog_title声明了响应这个请求的函数
    path('', views.blog_title, name='blog_title'),
    path('<int:article_id>/', views.blog_article, name='blog_article')
]

python-jango/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('account/', include('account.urls', namespace='account')),
    path('article/', include('article.urls', namespace='article'))
]

python-jango/mysite/templates/base.html
{% load static %}
<! DOCTYPE html>
    <html lang="zh-cn">
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=Edge">
        <meta charset="utf-8">
        <meta  name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://github.com/necolas/normalize.css/blob/master/normalize.css">
        <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">
    </head>
    <body>
        {% include 'header.html' %}
        <div class="container">
          {% block content %}
          {% endblock %}
        </div>
        {% include 'footer.html' %}
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% block javasript %}{% endblock %}
    </body>
    </html>

python-jango/mysite/templates/footer.html
<div class="container">
    <hr>
    <p class="text-center">............</p>
</div>

python-jango/mysite/templates/header.html
<!--# 模板中声明引入静态文件的标签 只有使用它，语句②（<a>标签）中才能使用 %static 'images/logo.png' %，而不是用“硬编码”的方式写图片地址-->
{% load static %}
    <div class="container">
        <nav class="navbar navbar-default" role="navigation">
            <div class="navbar-header">
                <a class="navbar-brand" href=" ">
<!--                    % static %可以用来引入某个静态文-->
<!--                  < img src="{% static '/images/logo.png' %}" width="100px">-->
                </a>
            </div>
            <div>
                <ul class="nav navbar-nav" role="navigation">
<!--                     url:Django模板内置的标记符，表示在此处返回由应用和参数组成的URL-->
                    <li><a href="{% url 'blog:blog_title' %}">BLOG</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
<!--                    user.is_authenticated则是返回用户登录的状-->
                    {% if user.is_authenticated %}
                        <li><a href="#">{{ user.username }}</a></li>
                        <li><a href="{% url 'account:user_logout' %}">Logout</a></li>
                        <li>
                            <div class="dropdown" style="margin-top:8px">
                              <button class='btn btn-default dropdown-toggle' type='button' id='dropdownMenu'
                                data-toggle='dropdown'>{{ user.username }}
                                  <span class='caret'></span>
                              </button>
                              <ul class="dropdown-menu">
                                  <li><a href="{% url 'account:password_change' %}">修改密码</a></li>
                                  <li><a href="{% url 'account:my_information' %}">个人信息</a></li>
                              </ul>
                            </div>
                        </li>
                    {% else %}
                        <li><a href="{% url 'account:user_login' %}">LOGIN</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </div>